# python Programming Assignment-13

#### Question 1. 
Write a program that calculates and prints the value according to the given formula:

#### Answer:
- Q = Square root of [(2 C D)/H]<br>
Following are the fixed values of C and H:<br>
C is 50. H is 30.<br>

- D is the variable whose values should be input to your program in a comma-separated sequence.<br>


Example<br>
- Let us assume the following comma separated input sequence is given to the program:<br>
100,150,180<br>
The output of the program should be:<br>
18,22,24

In [1]:
import math

def calculate_formula(args):
    c = 50;h = 30
    result = []
    for d in args:
        result.append(int(math.sqrt((2*c*int(d))/h)))
    return result
    
csv_in = list(input("Enter comma separated numbers input: ").split(','))
calculate_formula(csv_in)

Enter comma separated numbers input: 12,14,45,56,63,32,01


[6, 6, 12, 13, 14, 10, 1]

Question 2.
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. 
The element value in the i-th row and j-th column of the array should be i*j.

In [2]:
import numpy as np

X = int(input("Enter the value of X: "))
Y = int(input("Enter the value of Y: "))
arr = np.zeros((X, Y), dtype=int)

for i in range(X):
    for j in range(Y):
        arr[i][j] = i * j

print(arr)

Enter the value of X: 5
Enter the value of Y: 6
[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  5]
 [ 0  2  4  6  8 10]
 [ 0  3  6  9 12 15]
 [ 0  4  8 12 16 20]]


#### Question 3.
Write a program that accepts a comma separated sequence of words as input and
prints the words in a comma-separated sequence after sorting them alphabetically.

In [3]:
words = input("Enter a comma-separated sequence of words: ")

words_list = words.split(",")
words_list.sort()
sorted_words = ",".join(words_list)
print(sorted_words)

Enter a comma-separated sequence of words: love,faith,not,good
faith,good,love,not


#### Question 4. 
Write a program that accepts a sequence of whitespace separated words as input and prints the words
after removing all duplicate words and sorting them alphanumerically.

In [4]:
def remove_duplicates_and_sort_words(input_string):
    
    words = input_string.split()
    unique_words = list(set(words))
    sorted_words = sorted(unique_words)
    return ' '.join(sorted_words)

# input sentence : hello world, hello hari, hello ravi, hello world , Hello world!
input_sequence = input("Enter a sequence of whitespace separated words: ")
result = remove_duplicates_and_sort_words(input_sequence)
print("Result:", result)

Enter a sequence of whitespace separated words: love faith god yes
Result: faith god love yes


#### Question 5.
Write a program that accepts a sentence and calculate the number of letters and digits.

In [5]:
#Method 1
def count_letters_and_digits_1(sentence):
    letters = 0
    digits = 0

    for char in sentence:
        if char.isalpha():
            letters += 1
        elif char.isdigit():
            digits += 1

    return letters, digits

# input sentence : hello world! 123456!
sentence = input("Enter a sentence: ")
print()
letter_count, digit_count = count_letters_and_digits_1(sentence)
print("Number of letters:", letter_count)
print("Number of digits:", digit_count)

Enter a sentence: Within a nervous system, a neuron, neurone, or nerve cell is an electrically excitable cell that fires electric signals called action potentials across a neural network. Neurons communicate with other cells via synapses - specialized connections that commonly use minute amounts of chemical neurotransmitters to pass the electric signal from the presynaptic neuron to the target cell through the synaptic gap. The neuron is the main component of nervous tissue in all animals except sponges and placozoa. Non-animals like plants and fungi do not have nerve cells.
Number of letters: 468
Number of digits: 0


In [6]:
#Method 2
def count_letters_and_digits_2(sentence):    
    words = input("Enter a sentence: ")
    letters = 0
    digits = 0
    for c in words:
        if (ord(c) >= ord('a') and ord(c) <= ord('z')) or (ord(c) >= ord('A') and ord(c) <= ord('Z')):
            letters += 1
        elif ord(c) >= ord('0') and ord(c) <= ord('9'):
            digits += 1
    return letters, digits
            
# input sentence : hello world! 123456!
sentence = input("Enter a sentence: ")
letter_count, digit_count = count_letters_and_digits_2(sentence)
print("Number of letters:", letter_count)
print("Number of digits:", digit_count)

Enter a sentence: Within a nervous system, a neuron, neurone, or nerve cell is an electrically excitable cell that fires electric signals called action potentials across a neural network. Neurons communicate with other cells via synapses - specialized connections that commonly use minute amounts of chemical neurotransmitters to pass the electric signal from the presynaptic neuron to the target cell through the synaptic gap. The neuron is the main component of nervous tissue in all animals except sponges and placozoa. Non-animals like plants and fungi do not have nerve cells.
Enter a sentence: Within a nervous system, a neuron, neurone, or nerve cell is an electrically excitable cell that fires electric signals called action potentials across a neural network. Neurons communicate with other cells via synapses - specialized connections that commonly use minute amounts of chemical neurotransmitters to pass the electric signal from the presynaptic neuron to the target cell through the syna

#### Question 6.
A website requires the users to input username and password to register. 
Write a program to check the validity of password input by users.

In [12]:
def check_password_validity(password):
    #password length >= 8 characters
    if len(password) < 8:
        raise ValueError("Password should be at least 8 characters long")

    # Checking at least one uppercase, one lowercase, and one digit
    has_uppercase = False
    has_lowercase = False
    has_digit = False

    for char in password:
        if char.isupper():
            has_uppercase = True
        elif char.islower():
            has_lowercase = True
        elif char.isdigit():
            has_digit = True

    if not (has_uppercase and has_lowercase and has_digit):
        raise ValueError("Password should contain at least one uppercase letter, one lowercase letter, and one digit")


#input from user
password = input("Enter your password: ")

try:
    # Checking validity of the password
    check_password_validity(password)
    print(f'Password "{password}" is valid')
except ValueError as error:
    print(f'Password "{password}" is not valid Error:', str(error))


Enter your password: Karthik@9488723110
Password "Karthik@9488723110" is valid
